[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
nft = "CYKRXdd4hnrKkA2HpdJAMcmeUauYXDJ4D5hqrnXUsFDg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/anh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
