[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
mint_to = "D5GK8Kye78gjuDMMjRnkWH5a6KfNEXzex5mekXL3HLR2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
